version: '3'

services:
  
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1231:80"
    environment:
      PMA_ARBITRARY: 1
    links:
      - db

  db:
    image: mysql:8
    ports:
      - "984:3306"

    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/cnf:/etc/mysql/conf.d
    
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root123123